##热部署默认会重启
#spring.devtools.restart.enabled=true
#  #添加那个目录的文件需要restart
#spring.devtools.restart.additional-paths=src/main/java
#  #排除那个目录的文件不需要restart
#spring.devtools.restart.exclude=static/**,public/**

spring:
  devtools:
    restart:
      enabled: true
      poll-interval: 3000ms
      quiet-period: 2999ms
      log-condition-evaluation-delta: false

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://43.143.195.220:3306/pai_admin_go?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: pai_admin_go
      password: p4BjSFmwnaZGZifY

  redis:
    host: localhost
    port: 6379
    password: '010101'
    database: 2
    timeout: 5000

springfox:
  documentation:
    swagger-ui:
      enabled: true
      base-url: /doc

app:
  secret: yr62SYDYruCLe8XtdXDwp52uvYkbvoFJ
  token_key: 'admin:token:'
  token_ttl: 3600
  verify_ttl: 300
  # 根目录
  path: E:\\www\\pai-admin-java\\