spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pai_admin_go?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: pai_admin_go
      password: p4BjSFmwnaZGZifY

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
    timeout: 5000

springfox:
  documentation:
    swagger-ui:
      enabled: true
      base-url: /doc

app:
  token_key: 'admin:token:'
  token_ttl: 3600
  verify_ttl: 300
  # 根目录
  path: /www/wwwroot/pai-admin-java/